language: go
go:
  - "1.14"
install:
  - go get github.com/kisielk/errcheck
  - go get golang.org/x/lint/golint
script:
  - go get -d -t ./...
  - go test ./...
  - go vet ./...
  - errcheck ./...
  - golint ./...
